### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by kant01ne** [Skaelv/autocomplete-react#2]
Here is an example of an implementation of the current version working with multiple indexes:

![awesomescreenshot-2018-03-28t11-51-21-205z](https://user-images.githubusercontent.com/5072452/38027342-9a8aec42-328f-11e8-8387-57f137ab1d69.gif)

Keyboard navigation means that you can navigate through the Index lists and choose a Hit that will then be selected? For which purpose? Should we add a callback for the user to be able to trigger an action when an element from the list is selected?

**Comment by Skaelv** [comment]
Solution proposed:
[Dropdown not on focus/No value] KeyDown or KeyUp: Dropdown Focus
[Dropdown on focus/No value] KeyDown or KeyUp: Dropdown out of Focus

[Dropdown on focus/With value] KeyDown: Select the first element of the first list
    - [Dropdown on focus/With value and first element selected] KeyDown: Select the second element of the first list
   - [Dropdown on focus/With value and first element selected] KeyRight: Select the first element of the second list

- [Dropdown on focus/With value and any element of the second list selected] KeyRight: Select the first element of the FIRST list

...
