### ISSUE TITLE
Accessibility basic rules

### ISSUE THREAD

**Issue by kant01ne** [Skaelv/autocomplete-react#4]
I'm not sure what accessibility basic rules means in this context.

I've added the current behavior for context on what's been done yet and maybe to help explain what is asked.
![awesomescreenshot-2018-03-28t11-51-21-205z](https://user-images.githubusercontent.com/5072452/38027232-4c387afa-328f-11e8-870f-38a39c792c5d.gif)

**Comment by Skaelv** [comment]
![awesomescreenshot-2018-03-28t11-51-21-205z](https://user-images.githubusercontent.com/5072452/38027206-3dfae6e4-328f-11e8-900b-6a8859a260ab.gif)

**Comment by kant01ne** [comment]
Made some researchs on Google :)
Accessibility basic rules wraps a lot of common patterns on the web such as:
  - "error prevention",
 - "error identification",
 - "make all functionnalities keyboard accessible (dropdown, modals...)"
 - Focus order and visibility
 - Provide text alternatives

**Comment by kant01ne** [comment]
Those are most of the time covered by the Browser (focus order and visibility, modals and dropdown accessible by keyboard), error prevention and identification is well covered so far.
Closing the issue..
